---

- name : enable php5 mcrypt module
  shell: php5enmod mcrypt

- name: enable mod_rewrite
  shell: a2enmod rewrite

- name: restart apache
  service: name=apache2 state=restarted

- name: create link
  action: file state=link src=/var/www/html dest=/home/vagrant/www

